name: Ultraviolet-Node
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Runs the specified commands commands to get Ultraviolet-Node running.
      - name: localtunnel to output web
        run: |
          npm install -g localtunnel
          lt --port 8080
      - name: run ultraviolet
        run: |
          git clone https://github.com/titaniumnetwork-dev/Ultraviolet-Node --recursive
          cd Ultraviolet-Node
          npm install
          npm start
