name: Ultraviolet-Node
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Runs the specified commands commands to get Ultraviolet-Node running.
      - name: run ultraviolet
        run: |
          git clone https://github.com/titaniumnetwork-dev/Ultraviolet-Node --recursive
          cd Ultraviolet-Node
          npm install
          screen -dm npm start
      - name: tunnel and expose to web
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          sudo tar xvzf ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin
          screen -dm ngrok http 8080
          curl localhost:4040/api/tunnels
      - name: sleep
        run: sleep 999999999
