name: Ultraviolet-Node
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Runs the specified commands commands to get Ultraviolet-Node running.
      - name: run ultraviolet
        run: |
          git clone https://github.com/titaniumnetwork-dev/Ultraviolet-Node --recursive
          cd Ultraviolet-Node
          npm install
          screen -dm npm start
      - name: tunnel and expose to web
        run: |
          npm install -g localtunnel
          lt -p 8080
      - name: sleep
        run: sleep 999999999
